### PR TITLE
Lon 833

### PR DESCRIPTION
**Pull request by ylatuya**

### CODE REVIEW

**Comment by turran** [comment]
From the mappings and the change on the test file I assume that the files (projects, dashboards, etc)  will have the old types but once loaded will be mapped to the new types in memory, right?

In case of exporting, the mappings will be used on the other way around? that is, the files will be exported with the old types too?

For the DB case, are the types stored with the old types too? I suppose that's the DocumentType for, right?

**Comment by ylatuya** [comment]
These mappings are only used during the deserialization process, to convert the old type to new one, but new files will be now exported with the new types.

The DocumentType is used in the database to group several types in the same view. For example all classes derived from EventType (AnalysysEventType, PenaltyCardEventType, etc...) will share the same view, that filters by document type "EventType".

**Comment by turran** [comment]
:+1: 

Just to know how it works, in case a new type Foo changes in time into a new-new type Bar. Is just a matter to add the Foo into the mappings to Bar? that is, we can keep changing names as long as a new entry exists on the mappings.

**Comment by ylatuya** [comment]
There are 2 mechanism:

- a more generic one that renames namespaces, for example LongoMatch.Core -> Vas.Core so LongoMatch.Core.Common.Image can be mapped to Vas.Core.Common.Image (before checking if LongoMatch.Core.Common.Image exists)
- another one that does exact matching replacements, for example LongoMatch.Core.Store.Templates.Team to LongoMatch.Core.Store.Templates.SportsTeam.

There is cache for types, so the first time the type name is resolved to an instantiable type, it's cached and reused later.

We can add as many mappings as we want in the future

**Pull request merged**
